package router

import (
	"github.com/gin-gonic/gin"

	"github.com/ragflow-x/ragflow-x/internal/middleware"
	"github.com/ragflow-x/ragflow-x/internal/service"
)

// accessRules defines the (method, path) -> (action, resource) permission map
// enforced centrally at the middleware layer, with ABAC scope resolvers where
// the object carries tenant/project/owner attributes. Every route in the
// authenticated group must be registered here; the RBAC middleware denies any
// unregistered route by default.
func accessRules(svc *service.Service) []middleware.Rule {
	rules := []middleware.Rule{
		// Governance
		{Method: "GET", Path: "/api/v1/conversation/assistants", Action: "read", Resource: "assistant"},
		{Method: "PUT", Path: "/api/v1/conversation/assistants/:kind/:targetId", Action: "manage", Resource: "assistant"},
		{Method: "PUT", Path: "/api/v1/conversation/assistants/:kind/:targetId/governance", Action: "manage", Resource: "assistant"},
		{Method: "POST", Path: "/api/v1/conversation/route", Action: "execute", Resource: "assistant"},
		{Method: "POST", Path: "/api/v1/conversation/route/:routeId/select", Action: "execute", Resource: "assistant"},
		{Method: "POST", Path: "/api/v1/conversation/route-selections/:routeSelectionId/bootstrap", Action: "execute", Resource: "assistant"},
		{Method: "POST", Path: "/api/v1/conversation/routing/evaluations", Action: "manage", Resource: "assistant"},
		{Method: "GET", Path: "/api/v1/conversation/routing/evaluations", Action: "read", Resource: "assistant"},
		{Method: "GET", Path: "/api/v1/conversation/routing/evaluations/:runId", Action: "read", Resource: "assistant"},
		{Method: "GET", Path: "/api/v1/conversation/routing/policy", Action: "manage", Resource: "assistant"},
		{Method: "PUT", Path: "/api/v1/conversation/routing/policy", Action: "manage", Resource: "assistant"},
		{Method: "GET", Path: "/api/v1/auth/me", Action: "read", Resource: "user"},
		{Method: "GET", Path: "/api/v1/tenants", Action: "read", Resource: "tenant"},
		{Method: "GET", Path: "/api/v1/tenants/export", Action: "read", Resource: "tenant"},
		{Method: "GET", Path: "/api/v1/branding", Action: "read", Resource: "branding"},
		{Method: "PUT", Path: "/api/v1/branding", Action: "manage", Resource: "branding"},
		{Method: "POST", Path: "/api/v1/branding/logo", Action: "manage", Resource: "branding"},
		{Method: "GET", Path: "/api/v1/system/config", Action: "read", Resource: "system"},
		{Method: "GET", Path: "/api/v1/system/config/public-key", Action: "read", Resource: "system"},
		{Method: "POST", Path: "/api/v1/system/config/preflight", Action: "read", Resource: "system"},
		{Method: "POST", Path: "/api/v1/system/config/apply", Action: "manage", Resource: "system"},
		{Method: "GET", Path: "/api/v1/system/ragflow/sync/settings", Action: "read", Resource: "ragflow-sync"},
		{Method: "PATCH", Path: "/api/v1/system/ragflow/sync/settings", Action: "manage", Resource: "ragflow-sync"},
		{Method: "GET", Path: "/api/v1/system/ragflow/sync/mappings", Action: "read", Resource: "ragflow-sync"},
		{Method: "POST", Path: "/api/v1/system/ragflow/sync/mappings", Action: "manage", Resource: "ragflow-sync"},
		{Method: "DELETE", Path: "/api/v1/system/ragflow/sync/mappings/:externalTenantId", Action: "manage", Resource: "ragflow-sync"},
		{Method: "POST", Path: "/api/v1/system/ragflow/sync/scan", Action: "manage", Resource: "ragflow-sync"},
		{Method: "GET", Path: "/api/v1/system/ragflow/sync/runs", Action: "read", Resource: "ragflow-sync"},
		{Method: "GET", Path: "/api/v1/system/ragflow/sync/runs/:id", Action: "read", Resource: "ragflow-sync"},
		{Method: "GET", Path: "/api/v1/system/ragflow/sync/runs/:id/items", Action: "read", Resource: "ragflow-sync"},
		{Method: "POST", Path: "/api/v1/system/ragflow/sync/runs/:id/import", Action: "manage", Resource: "ragflow-sync"},
		{Method: "POST", Path: "/api/v1/system/ragflow/sync/runs/:id/assign", Action: "manage", Resource: "ragflow-sync"},
		{Method: "POST", Path: "/api/v1/system/ragflow/sync/reconcile", Action: "manage", Resource: "ragflow-sync"},
		{Method: "GET", Path: "/api/v1/system/ragflow/sync/resources", Action: "read", Resource: "ragflow-sync"},
		{Method: "GET", Path: "/api/v1/system/ragflow/sync/relink/tenant-options", Action: "read", Resource: "ragflow-sync"},
		{Method: "GET", Path: "/api/v1/system/ragflow/sync/relink/resource-options", Action: "read", Resource: "ragflow-sync"},
		{Method: "GET", Path: "/api/v1/system/ragflow/sync/resources/:type/:externalTenantId/:id/versions", Action: "read", Resource: "ragflow-sync"},
		{Method: "GET", Path: "/api/v1/system/ragflow/sync/artifacts/:id", Action: "read", Resource: "ragflow-sync"},
		{Method: "POST", Path: "/api/v1/system/ragflow/sync/resources/:type/:externalTenantId/:id/relink", Action: "manage", Resource: "ragflow-sync"},
		{Method: "POST", Path: "/api/v1/system/ragflow/sync/resources/:type/:externalTenantId/:id/conflicts/resolve", Action: "manage", Resource: "ragflow-sync"},
		{Method: "GET", Path: "/api/v1/system/settings", Action: "read", Resource: "system"},
		{Method: "PATCH", Path: "/api/v1/system/settings", Action: "manage", Resource: "system"},
		{Method: "GET", Path: "/api/v1/system/settings/revisions", Action: "read", Resource: "system"},
		{Method: "GET", Path: "/api/v1/system/settings/revisions/:id", Action: "read", Resource: "system"},
		{Method: "POST", Path: "/api/v1/system/settings/revisions/:id/rollback", Action: "manage", Resource: "system"},
		{Method: "POST", Path: "/api/v1/system/settings/secrets/:key", Action: "manage", Resource: "system"},
		{Method: "POST", Path: "/api/v1/tenants", Action: "manage", Resource: "tenant"},
		{Method: "PUT", Path: "/api/v1/tenants/status", Action: "manage", Resource: "tenant"},
		{Method: "PUT", Path: "/api/v1/tenants/:id", Action: "manage", Resource: "tenant"},
		{Method: "DELETE", Path: "/api/v1/tenants/:id", Action: "manage", Resource: "tenant"},

		{Method: "GET", Path: "/api/v1/users", Action: "read", Resource: "user"},
		{Method: "POST", Path: "/api/v1/users", Action: "manage", Resource: "user"},
		{Method: "PUT", Path: "/api/v1/users/:id/role", Action: "manage", Resource: "user"},
		{Method: "PUT", Path: "/api/v1/users/:id/status", Action: "manage", Resource: "user"},
		{Method: "PUT", Path: "/api/v1/users/:id", Action: "manage", Resource: "user"},
		{Method: "DELETE", Path: "/api/v1/users/:id", Action: "manage", Resource: "user"},

		{Method: "GET", Path: "/api/v1/roles", Action: "read", Resource: "role"},
		{Method: "GET", Path: "/api/v1/roles/permission-catalog", Action: "read", Resource: "role"},
		{Method: "POST", Path: "/api/v1/roles", Action: "manage", Resource: "role"},
		{Method: "PUT", Path: "/api/v1/roles/:id", Action: "manage", Resource: "role"},
		{Method: "DELETE", Path: "/api/v1/roles/:id", Action: "manage", Resource: "role"},
		{Method: "GET", Path: "/api/v1/roles/:id/permissions", Action: "read", Resource: "role"},
		{Method: "PUT", Path: "/api/v1/roles/:id/permissions", Action: "manage", Resource: "role"},

		{Method: "GET", Path: "/api/v1/approvals", Action: "read", Resource: "approval"},
		{Method: "POST", Path: "/api/v1/approvals", Action: "execute", Resource: "approval"},
		{Method: "GET", Path: "/api/v1/approvals/export", Action: "read", Resource: "approval"},
		{Method: "GET", Path: "/api/v1/approvals/:id", Action: "read", Resource: "approval"},
		{Method: "POST", Path: "/api/v1/approvals/:id/approve", Action: "execute", Resource: "approval"},
		{Method: "POST", Path: "/api/v1/approvals/:id/reject", Action: "execute", Resource: "approval"},
		{Method: "POST", Path: "/api/v1/approvals/:id/cancel", Action: "execute", Resource: "approval"},
		{Method: "POST", Path: "/api/v1/approvals/:id/retry", Action: "manage", Resource: "approval"},
		{Method: "POST", Path: "/api/v1/approvals/batch-approve", Action: "manage", Resource: "approval"},
		{Method: "POST", Path: "/api/v1/approvals/batch-reject", Action: "manage", Resource: "approval"},
		{Method: "GET", Path: "/api/v1/approval-delegations", Action: "read", Resource: "approval"},
		{Method: "POST", Path: "/api/v1/approval-delegations", Action: "read", Resource: "approval"},
		{Method: "DELETE", Path: "/api/v1/approval-delegations/:id", Action: "read", Resource: "approval"},
		{Method: "GET", Path: "/api/v1/approval-policies", Action: "read", Resource: "approval-policy"},
		{Method: "POST", Path: "/api/v1/approval-policies", Action: "manage", Resource: "approval-policy"},
		{Method: "PUT", Path: "/api/v1/approval-policies/:id", Action: "manage", Resource: "approval-policy"},
		{Method: "GET", Path: "/api/v1/chats", Action: "read", Resource: "chat"},
		{Method: "GET", Path: "/api/v1/chats/model-options", Action: "read", Resource: "chat"},
		{Method: "POST", Path: "/api/v1/chat/completions", Action: "execute", Resource: "chat"},
		{Method: "POST", Path: "/api/v1/chat/upload", Action: "execute", Resource: "chat"},
		{Method: "GET", Path: "/api/v1/chat/reference", Action: "read", Resource: "chat"},
		{Method: "GET", Path: "/api/v1/chat/document/chunks", Action: "read", Resource: "chat"},
		{Method: "GET", Path: "/api/v1/chat/document/preview", Action: "read", Resource: "chat"},
		{Method: "GET", Path: "/api/v1/chat/image", Action: "read", Resource: "chat"},
		{Method: "POST", Path: "/api/v1/chat/feedback", Action: "execute", Resource: "chat"},
		{Method: "POST", Path: "/api/v1/chats", Action: "manage", Resource: "chat"},
		{Method: "GET", Path: "/api/v1/search-apps", Action: "read", Resource: "search-app"},
		{Method: "POST", Path: "/api/v1/search-apps", Action: "manage", Resource: "search-app"},
		{Method: "GET", Path: "/api/v1/search-apps/model-options", Action: "read", Resource: "search-app"},
		{Method: "GET", Path: "/api/v1/search-apps/:id", Action: "read", Resource: "search-app"},
		{Method: "GET", Path: "/api/v1/search-apps/:id/config", Action: "read", Resource: "search-app"},
		{Method: "PUT", Path: "/api/v1/search-apps/:id", Action: "manage", Resource: "search-app"},
		{Method: "DELETE", Path: "/api/v1/search-apps/:id", Action: "manage", Resource: "search-app"},
		{Method: "POST", Path: "/api/v1/search-apps/:id/completion", Action: "execute", Resource: "search-app"},
		{Method: "POST", Path: "/api/v1/search-apps/:id/completion/stream", Action: "execute", Resource: "search-app"},
		{Method: "GET", Path: "/api/v1/memories", Action: "read", Resource: "memory"},
		{Method: "GET", Path: "/api/v1/memories/model-options", Action: "read", Resource: "memory"},
		{Method: "POST", Path: "/api/v1/memories", Action: "manage", Resource: "memory"},
		{Method: "GET", Path: "/api/v1/memories/:id", Action: "read", Resource: "memory"},
		{Method: "GET", Path: "/api/v1/memories/:id/config", Action: "read", Resource: "memory"},
		{Method: "PUT", Path: "/api/v1/memories/:id", Action: "manage", Resource: "memory"},
		{Method: "DELETE", Path: "/api/v1/memories/:id", Action: "manage", Resource: "memory"},
		{Method: "GET", Path: "/api/v1/memories/:id/messages", Action: "read", Resource: "memory"},
		{Method: "POST", Path: "/api/v1/memories/:id/messages", Action: "execute", Resource: "memory"},
		{Method: "GET", Path: "/api/v1/memories/:id/messages/search", Action: "execute", Resource: "memory"},
		{Method: "GET", Path: "/api/v1/memories/:id/messages/:messageId/content", Action: "read", Resource: "memory"},
		{Method: "PUT", Path: "/api/v1/memories/:id/messages/:messageId", Action: "manage", Resource: "memory"},
		{Method: "DELETE", Path: "/api/v1/memories/:id/messages/:messageId", Action: "manage", Resource: "memory"},
		{Method: "GET", Path: "/api/v1/agents", Action: "read", Resource: "agent"},
		{Method: "POST", Path: "/api/v1/agents", Action: "manage", Resource: "agent"},
		{Method: "GET", Path: "/api/v1/agents/:id", Action: "read", Resource: "agent"},
		{Method: "GET", Path: "/api/v1/agents/:id/detail", Action: "read", Resource: "agent"},
		{Method: "PUT", Path: "/api/v1/agents/:id", Action: "manage", Resource: "agent"},
		{Method: "POST", Path: "/api/v1/agents/:id/publish", Action: "manage", Resource: "agent"},
		{Method: "DELETE", Path: "/api/v1/agents/:id", Action: "manage", Resource: "agent"},
		{Method: "GET", Path: "/api/v1/agents/:id/versions", Action: "read", Resource: "agent"},
		{Method: "GET", Path: "/api/v1/agents/:id/versions/:versionId", Action: "read", Resource: "agent"},
		{Method: "POST", Path: "/api/v1/agents/:id/versions/:versionId/rollback", Action: "manage", Resource: "agent"},
		{Method: "GET", Path: "/api/v1/agents/:id/sessions", Action: "read", Resource: "agent"},
		{Method: "POST", Path: "/api/v1/agents/:id/sessions", Action: "session:create", Resource: "agent"},
		{Method: "GET", Path: "/api/v1/agents/:id/sessions/:sessionId", Action: "read", Resource: "agent"},
		{Method: "GET", Path: "/api/v1/agents/:id/sessions/:sessionId/messages", Action: "read", Resource: "agent"},
		{Method: "DELETE", Path: "/api/v1/agents/:id/sessions/:sessionId", Action: "manage", Resource: "agent"},
		{Method: "POST", Path: "/api/v1/agents/:id/upload", Action: "execute", Resource: "agent"},
		{Method: "POST", Path: "/api/v1/agents/:id/chat/completions", Action: "execute", Resource: "agent"},
		{Method: "POST", Path: "/api/v1/agents/:id/chat/completions/stream", Action: "execute", Resource: "agent"},
		{Method: "POST", Path: "/api/v1/chats/batch-status", Action: "manage", Resource: "chat"},
		{Method: "DELETE", Path: "/api/v1/chats", Action: "manage", Resource: "chat"},
		{Method: "GET", Path: "/api/v1/chats/:id", Action: "read", Resource: "chat"},
		{Method: "GET", Path: "/api/v1/chats/:id/usage", Action: "read", Resource: "chat"},
		{Method: "GET", Path: "/api/v1/chats/:id/config", Action: "read", Resource: "chat"},
		{Method: "PUT", Path: "/api/v1/chats/:id", Action: "manage", Resource: "chat"},
		{Method: "DELETE", Path: "/api/v1/chats/:id", Action: "manage", Resource: "chat"},
		{Method: "GET", Path: "/api/v1/chats/:id/sessions", Action: "read", Resource: "chat"},
		{Method: "POST", Path: "/api/v1/chats/:id/sessions", Action: "manage", Resource: "chat"},
		{Method: "GET", Path: "/api/v1/chats/:id/sessions/:sessionId", Action: "read", Resource: "chat"},
		{Method: "GET", Path: "/api/v1/chats/:id/sessions/:sessionId/messages", Action: "read", Resource: "chat"},
		{Method: "PATCH", Path: "/api/v1/chats/:id/sessions/:sessionId", Action: "manage", Resource: "chat"},
		{Method: "DELETE", Path: "/api/v1/chats/:id/sessions/:sessionId", Action: "manage", Resource: "chat"},
		{Method: "DELETE", Path: "/api/v1/chats/:id/sessions", Action: "manage", Resource: "chat"},

		{Method: "GET", Path: "/api/v1/teams", Action: "read", Resource: "team"},
		{Method: "GET", Path: "/api/v1/teams/:id", Action: "read", Resource: "team"},
		{Method: "POST", Path: "/api/v1/teams", Action: "manage", Resource: "team"},
		{Method: "PUT", Path: "/api/v1/teams/:id", Action: "manage", Resource: "team"},
		{Method: "DELETE", Path: "/api/v1/teams/:id", Action: "manage", Resource: "team"},
		{Method: "GET", Path: "/api/v1/teams/:id/users", Action: "read", Resource: "team"},
		{Method: "POST", Path: "/api/v1/teams/:id/users", Action: "manage", Resource: "team"},
		{Method: "DELETE", Path: "/api/v1/teams/:id/users/:userId", Action: "manage", Resource: "team"},
		{Method: "GET", Path: "/api/v1/teams/:id/projects", Action: "read", Resource: "team"},
		{Method: "PUT", Path: "/api/v1/teams/:id/projects", Action: "manage", Resource: "team"},

		// Content
		{Method: "GET", Path: "/api/v1/projects", Action: "read", Resource: "project"},
		{Method: "POST", Path: "/api/v1/projects", Action: "manage", Resource: "project"},
		{Method: "GET", Path: "/api/v1/projects/:id", Action: "read", Resource: "project", Resolve: resolveProjectScope(svc)},
		{Method: "PUT", Path: "/api/v1/projects/:id", Action: "manage", Resource: "project"},
		{Method: "DELETE", Path: "/api/v1/projects/:id", Action: "manage", Resource: "project"},
		{Method: "GET", Path: "/api/v1/projects/:id/users", Action: "read", Resource: "project", Resolve: resolveProjectScope(svc)},
		{Method: "POST", Path: "/api/v1/projects/:id/users", Action: "manage", Resource: "project"},
		{Method: "DELETE", Path: "/api/v1/projects/:id/users/:userId", Action: "manage", Resource: "project"},
		{Method: "GET", Path: "/api/v1/projects/:id/datasets", Action: "read", Resource: "project", Resolve: resolveProjectScope(svc)},
		{Method: "PUT", Path: "/api/v1/projects/:id/datasets", Action: "manage", Resource: "project"},
		{Method: "GET", Path: "/api/v1/projects/:id/teams", Action: "read", Resource: "project", Resolve: resolveProjectScope(svc)},
		{Method: "PUT", Path: "/api/v1/projects/:id/teams", Action: "manage", Resource: "project"},

		{Method: "GET", Path: "/api/v1/datasets", Action: "read", Resource: "dataset"},
		{Method: "GET", Path: "/api/v1/datasets/model-options", Action: "read", Resource: "dataset"},
		{Method: "POST", Path: "/api/v1/datasets", Action: "manage", Resource: "dataset"},
		{Method: "PUT", Path: "/api/v1/datasets/:id/project", Action: "manage", Resource: "dataset"},
		{Method: "GET", Path: "/api/v1/datasets/:id/config", Action: "read", Resource: "dataset", Resolve: resolveDatasetScope(svc)},
		{Method: "PUT", Path: "/api/v1/datasets/:id/config", Action: "manage", Resource: "dataset", Resolve: resolveDatasetScope(svc)},
		{Method: "DELETE", Path: "/api/v1/datasets", Action: "manage", Resource: "dataset"},
		{Method: "GET", Path: "/api/v1/datasets/export", Action: "read", Resource: "dataset-export"},
		{Method: "GET", Path: "/api/v1/datasets/:id", Action: "read", Resource: "dataset", Resolve: resolveDatasetScope(svc)},
		{Method: "DELETE", Path: "/api/v1/datasets/:id", Action: "manage", Resource: "dataset", Resolve: resolveDatasetScope(svc)},
		{Method: "PUT", Path: "/api/v1/datasets/:id", Action: "manage", Resource: "dataset", Resolve: resolveDatasetScope(svc)},

		{Method: "GET", Path: "/api/v1/datasets/:id/documents", Action: "read", Resource: "document"},
		{Method: "POST", Path: "/api/v1/datasets/:id/documents", Action: "append", Resource: "document"},
		{Method: "GET", Path: "/api/v1/datasets/:id/incremental", Action: "read", Resource: "document"},
		{Method: "POST", Path: "/api/v1/datasets/:id/incremental/scan", Action: "execute", Resource: "document"},
		{Method: "POST", Path: "/api/v1/datasets/:id/parse", Action: "execute", Resource: "document"},
		{Method: "POST", Path: "/api/v1/datasets/:id/documents/stop", Action: "execute", Resource: "document"},
		{Method: "DELETE", Path: "/api/v1/datasets/:id/documents", Action: "delete:own", Resource: "document"},
		{Method: "POST", Path: "/api/v1/datasets/:id/documents/status", Action: "execute", Resource: "document"},
		{Method: "PUT", Path: "/api/v1/datasets/:id/documents/:docId/metadata", Action: "execute", Resource: "document"},
		{Method: "GET", Path: "/api/v1/datasets/:id/documents/:docId/chunks", Action: "read", Resource: "document"},
		{Method: "GET", Path: "/api/v1/datasets/:id/documents/:docId/preview", Action: "read", Resource: "document"},
		{Method: "DELETE", Path: "/api/v1/datasets/:id/documents/:docId/chunks", Action: "execute", Resource: "document"},
		{Method: "PATCH", Path: "/api/v1/datasets/:id/documents/:docId/chunks", Action: "execute", Resource: "document"},

		{Method: "GET", Path: "/api/v1/tasks/jobs", Action: "read", Resource: "task"},
		{Method: "GET", Path: "/api/v1/tasks", Action: "read", Resource: "task"},
		{Method: "DELETE", Path: "/api/v1/tasks", Action: "manage", Resource: "task"},
		{Method: "POST", Path: "/api/v1/tasks/sync", Action: "execute", Resource: "task"},

		// Model & gateway
		{Method: "GET", Path: "/api/v1/model-providers", Action: "read", Resource: "model-provider"},
		{Method: "POST", Path: "/api/v1/model-providers", Action: "manage", Resource: "model-provider"},
		{Method: "GET", Path: "/api/v1/model-providers/catalog", Action: "read", Resource: "model-provider"},
		{Method: "GET", Path: "/api/v1/model-providers/:id", Action: "read", Resource: "model-provider"},
		{Method: "DELETE", Path: "/api/v1/model-providers/:id", Action: "manage", Resource: "model-provider"},
		{Method: "GET", Path: "/api/v1/model-providers/:id/instances", Action: "read", Resource: "model-provider"},
		{Method: "POST", Path: "/api/v1/model-providers/:id/instances", Action: "manage", Resource: "model-provider"},
		{Method: "PUT", Path: "/api/v1/model-providers/:id/instances/:instanceId", Action: "manage", Resource: "model-provider"},
		{Method: "DELETE", Path: "/api/v1/model-providers/:id/instances", Action: "manage", Resource: "model-provider"},
		{Method: "POST", Path: "/api/v1/model-providers/:id/verify", Action: "execute", Resource: "model-provider"},
		{Method: "GET", Path: "/api/v1/model-providers/:id/instances/:instanceId/models", Action: "read", Resource: "model-provider"},
		{Method: "POST", Path: "/api/v1/model-providers/:id/instances/:instanceId/models", Action: "manage", Resource: "model-provider"},
		{Method: "PATCH", Path: "/api/v1/model-providers/:id/instances/:instanceId/models/:modelId", Action: "manage", Resource: "model-provider"},
		{Method: "DELETE", Path: "/api/v1/model-providers/:id/instances/:instanceId/models", Action: "manage", Resource: "model-provider"},
		{Method: "POST", Path: "/api/v1/model-providers/:id/instances/:instanceId/models/:modelId/test", Action: "execute", Resource: "model-provider"},
		{Method: "GET", Path: "/api/v1/enterprise-connections", Action: "read", Resource: "enterprise-connection"},
		{Method: "POST", Path: "/api/v1/enterprise-connections", Action: "manage", Resource: "enterprise-connection"},
		{Method: "GET", Path: "/api/v1/enterprise-connections/:id", Action: "read", Resource: "enterprise-connection"},
		{Method: "PUT", Path: "/api/v1/enterprise-connections/:id", Action: "manage", Resource: "enterprise-connection"},
		{Method: "GET", Path: "/api/v1/enterprise-connections/:id/versions", Action: "read", Resource: "enterprise-connection"},
		{Method: "POST", Path: "/api/v1/enterprise-connections/:id/rotate-credential", Action: "manage", Resource: "enterprise-connection"},
		{Method: "POST", Path: "/api/v1/enterprise-connections/:id/deprecate", Action: "manage", Resource: "enterprise-connection"},
		{Method: "POST", Path: "/api/v1/enterprise-connections/:id/retire", Action: "manage", Resource: "enterprise-connection"},
		{Method: "POST", Path: "/api/v1/enterprise-connections/:id/test", Action: "test", Resource: "enterprise-connection"},
		{Method: "GET", Path: "/api/v1/enterprise-connections/:id/health", Action: "read", Resource: "enterprise-connection"},
		{Method: "GET", Path: "/api/v1/enterprise-connections/:id/availability", Action: "read", Resource: "enterprise-connection"},
		{Method: "GET", Path: "/api/v1/enterprise-connections/:id/bindings", Action: "read", Resource: "enterprise-connection"},
		{Method: "GET", Path: "/api/v1/enterprise-connections/:id/bindings/:bindingId", Action: "read", Resource: "enterprise-connection"},
		{Method: "POST", Path: "/api/v1/enterprise-connections/:id/bindings", Action: "manage", Resource: "enterprise-connection"},
		{Method: "PUT", Path: "/api/v1/enterprise-connections/:id/bindings/:bindingId", Action: "manage", Resource: "enterprise-connection"},
		{Method: "POST", Path: "/api/v1/enterprise-connections/:id/bindings/:bindingId/revoke", Action: "manage", Resource: "enterprise-connection"},
		{Method: "GET", Path: "/api/v1/enterprise-connections/:id/bindings/:bindingId/versions", Action: "read", Resource: "enterprise-connection"},
		{Method: "GET", Path: "/api/v1/model-routes", Action: "read", Resource: "model-route"},
		{Method: "POST", Path: "/api/v1/model-routes", Action: "manage", Resource: "model-route"},
		{Method: "PUT", Path: "/api/v1/model-routes/:id", Action: "manage", Resource: "model-route"},
		{Method: "DELETE", Path: "/api/v1/model-routes/:id", Action: "manage", Resource: "model-route"},
		{Method: "POST", Path: "/api/v1/model-routes/:id/enterprise-pin", Action: "manage", Resource: "model-route"},
		{Method: "GET", Path: "/api/v1/model-routes/:id/enterprise-pins", Action: "read", Resource: "model-route"},
		{Method: "GET", Path: "/api/v1/keys", Action: "read", Resource: "api-key"},
		{Method: "POST", Path: "/api/v1/keys", Action: "manage", Resource: "api-key"},
		{Method: "POST", Path: "/api/v1/keys/:id/revoke", Action: "manage", Resource: "api-key"},

		// Operations
		{Method: "GET", Path: "/api/v1/usage", Action: "read", Resource: "usage"},
		{Method: "GET", Path: "/api/v1/usage/details", Action: "read", Resource: "usage"},
		{Method: "GET", Path: "/api/v1/audit", Action: "read", Resource: "audit"},
		{Method: "GET", Path: "/api/v1/usage/export", Action: "read", Resource: "usage-export"},
		{Method: "GET", Path: "/api/v1/audit/export", Action: "read", Resource: "audit"},
		{Method: "GET", Path: "/api/v1/audit/anchors", Action: "read", Resource: "audit-anchor"},
		{Method: "GET", Path: "/api/v1/audit/verify", Action: "read", Resource: "audit"},
		{Method: "POST", Path: "/api/v1/audit/repair", Action: "manage", Resource: "audit"},
		{Method: "GET", Path: "/api/v1/dashboard", Action: "read", Resource: "dashboard"},
		{Method: "GET", Path: "/api/v1/knowledge-ops", Action: "read", Resource: "knowledge-ops"},
		{Method: "GET", Path: "/api/v1/knowledge-ops/top-queries", Action: "read", Resource: "knowledge-ops"},
		{Method: "GET", Path: "/api/v1/knowledge-ops/events", Action: "read", Resource: "knowledge-ops"},
		{Method: "PATCH", Path: "/api/v1/knowledge-ops/events/:id/review", Action: "manage", Resource: "knowledge-ops"},
		{Method: "GET", Path: "/api/v1/workbench/recent-sessions", Action: "read", Resource: "assistant"},
		{Method: "GET", Path: "/api/v1/scenario-template-assets", Action: "read", Resource: "scenario-template"},
		{Method: "POST", Path: "/api/v1/scenario-template-assets", Action: "manage", Resource: "scenario-template"},
		{Method: "POST", Path: "/api/v1/scenario-template-assets/import", Action: "manage", Resource: "scenario-template"},
		{Method: "PUT", Path: "/api/v1/scenario-template-assets/:id", Action: "manage", Resource: "scenario-template"},
		{Method: "GET", Path: "/api/v1/scenario-template-assets/:id", Action: "read", Resource: "scenario-template"},
		{Method: "GET", Path: "/api/v1/scenario-template-assets/:id/export", Action: "read", Resource: "scenario-template"},
		{Method: "POST", Path: "/api/v1/scenario-template-assets/:id/copy", Action: "manage", Resource: "scenario-template"},
		{Method: "DELETE", Path: "/api/v1/scenario-template-assets/:id", Action: "manage", Resource: "scenario-template"},
		{Method: "POST", Path: "/api/v1/scenario-template-assets/:id/eval-set", Action: "manage", Resource: "eval-set"},
		{Method: "POST", Path: "/api/v1/scenario-template-assets/:id/release-candidate", Action: "manage", Resource: "release-governance"},
		{Method: "POST", Path: "/api/v1/scenario-template-assets/:id/instantiate-chat", Action: "manage", Resource: "chat"},
		{Method: "GET", Path: "/api/v1/prompt-policies", Action: "read", Resource: "prompt-policy"},
		{Method: "POST", Path: "/api/v1/prompt-policies", Action: "manage", Resource: "prompt-policy"},
		{Method: "GET", Path: "/api/v1/prompt-policies/:id", Action: "read", Resource: "prompt-policy"},
		{Method: "POST", Path: "/api/v1/prompt-policies/:id/rollback", Action: "manage", Resource: "prompt-policy"},
		{Method: "DELETE", Path: "/api/v1/prompt-policies/:id", Action: "manage", Resource: "prompt-policy"},
		{Method: "GET", Path: "/api/v1/knowledge-lifecycle", Action: "read", Resource: "knowledge-lifecycle"},
		{Method: "PUT", Path: "/api/v1/datasets/:id/lifecycle", Action: "manage", Resource: "knowledge-lifecycle"},
		{Method: "GET", Path: "/api/v1/eval-sets", Action: "read", Resource: "eval-set"},
		{Method: "POST", Path: "/api/v1/eval-sets", Action: "manage", Resource: "eval-set"},
		{Method: "POST", Path: "/api/v1/eval-sets/generate-from-templates", Action: "manage", Resource: "eval-set"},
		{Method: "GET", Path: "/api/v1/eval-sets/:id", Action: "read", Resource: "eval-set"},
		{Method: "PUT", Path: "/api/v1/eval-sets/:id", Action: "manage", Resource: "eval-set"},
		{Method: "DELETE", Path: "/api/v1/eval-sets/:id", Action: "manage", Resource: "eval-set"},
		{Method: "POST", Path: "/api/v1/knowledge-ops/events/:id/to-eval-case", Action: "manage", Resource: "eval-set"},
		{Method: "GET", Path: "/api/v1/governance/overview", Action: "read", Resource: "scenario-template"},
		{Method: "GET", Path: "/api/v1/release-candidates", Action: "read", Resource: "release-governance"},
		{Method: "GET", Path: "/api/v1/execution-snapshots", Action: "read", Resource: "release-governance"},
		{Method: "POST", Path: "/api/v1/release-candidates", Action: "manage", Resource: "release-governance"},
		{Method: "POST", Path: "/api/v1/release-candidates/:id/ready", Action: "manage", Resource: "release-governance"},
		{Method: "POST", Path: "/api/v1/execution-snapshots", Action: "manage", Resource: "release-governance"},
		{Method: "POST", Path: "/api/v1/evaluation-set-versions", Action: "manage", Resource: "release-governance"},
		{Method: "POST", Path: "/api/v1/evaluation-case-versions", Action: "manage", Resource: "release-governance"},
		{Method: "POST", Path: "/api/v1/evaluation-runs", Action: "manage", Resource: "release-governance"},
		{Method: "POST", Path: "/api/v1/evaluation-runs/:id/case-results", Action: "manage", Resource: "release-governance"},
		{Method: "POST", Path: "/api/v1/evaluation-runs/:id/complete", Action: "manage", Resource: "release-governance"},
		{Method: "GET", Path: "/api/v1/evaluation-runs", Action: "read", Resource: "release-governance"},
		{Method: "POST", Path: "/api/v1/evidence-bundles", Action: "manage", Resource: "release-governance"},
		{Method: "GET", Path: "/api/v1/evidence-bundles", Action: "read", Resource: "release-governance"},
		{Method: "POST", Path: "/api/v1/release-gates", Action: "manage", Resource: "release-governance"},
		{Method: "GET", Path: "/api/v1/release-gates", Action: "read", Resource: "release-governance"},
		{Method: "POST", Path: "/api/v1/releases", Action: "manage", Resource: "release-governance"},
		{Method: "POST", Path: "/api/v1/releases/:id/complete", Action: "manage", Resource: "release-governance"},
		{Method: "POST", Path: "/api/v1/releases/:id/rollback", Action: "manage", Resource: "release-governance"},
		{Method: "GET", Path: "/api/v1/releases", Action: "read", Resource: "release-governance"},
		{Method: "GET", Path: "/api/v1/quality-issues", Action: "read", Resource: "release-governance"},
		{Method: "POST", Path: "/api/v1/quality-issues", Action: "manage", Resource: "release-governance"},
		{Method: "POST", Path: "/api/v1/quality-issues/:id/state", Action: "manage", Resource: "release-governance"},
		{Method: "POST", Path: "/api/v1/quality-issues/:id/verify", Action: "manage", Resource: "release-governance"},
		{Method: "GET", Path: "/api/v1/system/health", Action: "read", Resource: "system-health"},
		{Method: "GET", Path: "/api/v1/alerts", Action: "read", Resource: "alert"},
		{Method: "GET", Path: "/api/v1/alerts/deliveries", Action: "read", Resource: "alert"},
		{Method: "POST", Path: "/api/v1/alerts/:id/deliveries/:channel/retry", Action: "manage", Resource: "alert"},
		{Method: "POST", Path: "/api/v1/alerts/:id/read", Action: "manage", Resource: "alert"},
		{Method: "POST", Path: "/api/v1/alerts/:id/claim", Action: "manage", Resource: "alert"},
		{Method: "GET", Path: "/api/v1/system/capabilities", Action: "read", Resource: "system"},
		{Method: "POST", Path: "/api/v1/system/capabilities/verify", Action: "manage", Resource: "system"},
	}
	return withRouteContracts(rules)
}

func resolveDatasetScope(svc *service.Service) middleware.ResolveContext {
	return func(c *gin.Context) (string, string, string, error) {
		tenantID := c.GetString(middleware.ContextTenantID)
		link, err := svc.Store.GetDatasetLink(c.Request.Context(), tenantID, c.Param("id"))
		if err != nil {
			// Fail closed: scope resolution errors must deny the request rather
			// than degrade to a weak tenant-only check.
			return "", "", "", err
		}
		if link == nil {
			return tenantID, "", "", nil
		}
		return tenantID, link.ProjectID, "", nil
	}
}

func resolveProjectScope(svc *service.Service) middleware.ResolveContext {
	return func(c *gin.Context) (string, string, string, error) {
		tenantID := c.GetString(middleware.ContextTenantID)
		p, err := svc.Store.GetProject(c.Request.Context(), tenantID, c.Param("id"))
		if err != nil {
			return "", "", "", err
		}
		if p == nil {
			return tenantID, "", "", nil
		}
		return tenantID, p.ID, "", nil
	}
}
