// Package router wires middleware and HTTP routes into a Gin engine.
package router

import (
	"path/filepath"
	"time"

	"github.com/gin-gonic/gin"

	"github.com/ragflow-x/ragflow-x/internal/config"
	"github.com/ragflow-x/ragflow-x/internal/handler"
	"github.com/ragflow-x/ragflow-x/internal/middleware"
	"github.com/ragflow-x/ragflow-x/internal/obs"
	"github.com/ragflow-x/ragflow-x/internal/pkg/ratelimit"
)

// New builds the Gin engine with all routes and middleware applied.
func New(cfg config.Config, h *handler.Handler, limiter ratelimit.Limiter) *gin.Engine {
	gin.SetMode(ginMode(cfg.Server.Mode))

	r := gin.New()
	r.Use(
		middleware.DynamicSecurityHeaders(h.Service.CurrentSecurityConfig),
		middleware.DynamicCORS(h.Service.CurrentSecurityConfig),
		obs.Get().Middleware(),
		middleware.Recovery(),
		middleware.RequestID(cfg.App.RequestIDHeader),
		middleware.RequestLogger(),
		middleware.DynamicBodyLimit(func() int64 { return h.Service.CurrentSecurityConfig().MaxRequestBytes }),
	)
	// Only expose the logos subdirectory publicly; the rest of DataDir stays private.
	r.Static("/api/v1/static/logos", filepath.Join(cfg.App.DataDir, "logos"))
	if cfg.Observability.MetricsEnabled {
		r.GET(cfg.Observability.MetricsPath, middleware.DynamicMetricsAuth(func() (string, []string) {
			observability := h.Service.CurrentObservabilityConfig()
			return observability.MetricsToken, observability.MetricsAllowCIDRs
		}), obs.Get().MetricsHandler())
	}
	if limiter == nil {
		limiter = ratelimit.NewMemory()
	}

	api := r.Group("/api/v1")

	api.GET("/health", h.Health)
	api.GET("/healthz", h.Health)
	api.GET("/readyz", h.Ready)
	api.GET("/branding/public", h.PublicBranding)

	auth := api.Group("/auth")
	auth.POST("/login", h.Login)
	auth.POST("/refresh", h.Refresh)
	auth.POST("/logout", h.Logout)
	auth.GET("/oidc/status", h.OIDCStatus)
	auth.GET("/oidc/start", middleware.RateLimit(limiter, middleware.ClientIPKey, 30, time.Minute), h.OIDCStart)
	auth.GET("/oidc/callback", middleware.RateLimit(limiter, middleware.ClientIPKey, 30, time.Minute), h.OIDCCallback)

	setup := api.Group("/system/setup")
	setup.GET("/status", h.SetupStatus)
	setup.POST("/admin", middleware.RateLimit(limiter, middleware.ClientIPKey, int64(cfg.Setup.RateLimitPerMin), time.Minute), h.SetupAdmin)
	setup.POST("/preflight", middleware.RateLimit(limiter, middleware.ClientIPKey, int64(cfg.Setup.RateLimitPerMin), time.Minute), h.Preflight)
	setup.GET("/public-key", h.SetupPublicKey)
	setup.POST("/apply", middleware.RateLimit(limiter, middleware.ClientIPKey, int64(cfg.Setup.RateLimitPerMin), time.Minute), h.SetupApply)

	api.POST("/system/settings/runtime/report",
		middleware.RateLimit(limiter, middleware.ClientIPKey, int64(cfg.Setup.RateLimitPerMin), time.Minute),
		middleware.RuntimeReportAuth(h.Service.CurrentRuntimeReportToken),
		h.ReportRuntimeSettingState,
	)

	protected := api.Group("/")
	protected.Use(middleware.DynamicCookieCSRF(func() []string {
		return h.Service.CurrentSecurityConfig().AllowedOrigins
	}))
	protected.Use(middleware.Auth(h.Service.JWT, h.Service))
	protected.Use(middleware.RBAC(h.Service, accessRules(h.Service)))
	{
		protected.GET("/conversation/assistants", h.ListConversationAssistants)
		protected.PUT("/conversation/assistants/:kind/:targetId", h.UpdateConversationAssistant)
		protected.PUT("/conversation/assistants/:kind/:targetId/governance", h.UpdateConversationAssistantGovernance)
		handler.RegisterReleaseGovernanceRoutes(protected, h)
		protected.POST("/conversation/route", h.RouteConversation)
		protected.POST("/conversation/route/:routeId/select", h.SelectRouteCandidate)
		protected.POST("/conversation/route-selections/:routeSelectionId/bootstrap", h.BootstrapRouteSelection)
		protected.POST("/conversation/routing/evaluations", h.RunRouteEvaluation)
		protected.GET("/conversation/routing/evaluations", h.ListRouteEvaluationRuns)
		protected.GET("/conversation/routing/evaluations/:runId", h.GetRouteEvaluationRun)
		protected.GET("/conversation/routing/policy", h.GetTenantRoutePolicy)
		protected.PUT("/conversation/routing/policy", h.SetTenantRoutePolicy)
		protected.GET("/auth/me", h.Me)
		protected.GET("/branding", h.GetBranding)
		protected.PUT("/branding", h.SetBranding)
		protected.POST("/branding/logo", h.UploadBrandingLogo)
		protected.GET("/tenants", h.ListTenants)
		protected.GET("/tenants/export", h.ExportTenants)
		protected.POST("/tenants", h.CreateTenant)
		protected.PUT("/tenants/status", h.BatchUpdateTenantStatus)
		protected.PUT("/tenants/:id", h.UpdateTenant)
		protected.DELETE("/tenants/:id", h.DeleteTenant)
		protected.GET("/teams", h.ListTeams)
		protected.GET("/teams/:id", h.GetTeam)
		protected.POST("/teams", h.CreateTeam)
		protected.PUT("/teams/:id", h.UpdateTeam)
		protected.DELETE("/teams/:id", h.DeleteTeam)
		protected.GET("/teams/:id/users", h.ListTeamUsers)
		protected.POST("/teams/:id/users", h.AddTeamUser)
		protected.DELETE("/teams/:id/users/:userId", h.RemoveTeamUser)
		protected.GET("/projects", h.ListProjects)
		protected.GET("/teams/:id/projects", h.ListTeamProjects)
		protected.PUT("/teams/:id/projects", h.BindTeamProjects)
		protected.POST("/projects", h.CreateProject)
		protected.GET("/projects/:id", h.GetProject)
		protected.PUT("/projects/:id", h.UpdateProject)
		protected.DELETE("/projects/:id", h.DeleteProject)
		protected.GET("/projects/:id/users", h.ListProjectUsers)
		protected.POST("/projects/:id/users", h.AddProjectUser)
		protected.DELETE("/projects/:id/users/:userId", h.RemoveProjectUser)
		protected.GET("/projects/:id/datasets", h.GetProjectDatasets)
		protected.PUT("/projects/:id/datasets", h.BindProjectDatasets)
		protected.GET("/projects/:id/teams", h.GetProjectTeams)
		protected.PUT("/projects/:id/teams", h.BindProjectTeams)
		protected.GET("/datasets", h.ListAllDatasets)
		protected.GET("/datasets/model-options", h.GetDatasetModelOptions)
		protected.GET("/datasets/:id", h.GetDataset)
		protected.DELETE("/datasets/:id", h.DeleteDataset)
		protected.PUT("/datasets/:id", h.UpdateDataset)
		protected.GET("/datasets/export", h.ExportDatasets)
		protected.DELETE("/datasets", h.DeleteDatasets)
		protected.PUT("/datasets/:id/project", h.BindDatasetProject)
		protected.GET("/datasets/:id/config", h.GetDatasetConfig)
		protected.PUT("/datasets/:id/config", h.UpdateDatasetConfig)
		protected.POST("/datasets", h.CreateDataset)
		protected.GET("/datasets/:id/documents", h.ListDocuments)
		protected.POST("/datasets/:id/documents", h.UploadDocument)
		protected.GET("/datasets/:id/incremental", h.ListIncrementalLedger)
		protected.POST("/datasets/:id/incremental/scan", h.ApplyIncrementalSourceBatch)
		protected.POST("/datasets/:id/parse", h.ParseDocuments)
		protected.POST("/datasets/:id/documents/stop", h.StopDocuments)
		protected.DELETE("/datasets/:id/documents", h.DeleteDocuments)
		protected.POST("/datasets/:id/documents/status", h.SetDocumentsStatus)
		protected.PUT("/datasets/:id/documents/:docId/metadata", h.UpdateDocumentMetadata)
		protected.GET("/datasets/:id/documents/:docId/chunks", h.ListDocumentChunks)
		protected.GET("/datasets/:id/documents/:docId/preview", h.PreviewDocument)
		protected.DELETE("/datasets/:id/documents/:docId/chunks", h.DeleteDocumentChunks)
		protected.PATCH("/datasets/:id/documents/:docId/chunks", h.SetDocumentChunksAvailable)
		protected.GET("/dashboard", h.Dashboard)
		protected.GET("/knowledge-ops", h.KnowledgeOpsSummary)
		protected.GET("/knowledge-ops/top-queries", h.KnowledgeOpsTopQueries)
		protected.GET("/knowledge-ops/events", h.KnowledgeOpsEvents)
		protected.PATCH("/knowledge-ops/events/:id/review", h.ReviewKnowledgeOpsEvent)
		protected.GET("/workbench/recent-sessions", h.RecentCrossAppSessions)
		protected.GET("/tasks/jobs", h.ListJobs)
		protected.GET("/tasks", h.ListTasks)
		protected.DELETE("/tasks", h.DeleteTasks)
		protected.POST("/tasks/sync", h.SyncTasks)
		protected.GET("/usage", h.Usage)
		protected.GET("/usage/details", h.UsageDetail)
		protected.GET("/usage/export", h.ExportUsageReport)
		protected.GET("/audit", h.ListAudits)
		protected.GET("/audit/export", h.ExportAudits)
		protected.GET("/audit/anchors", h.ListAuditAnchors)
		protected.GET("/audit/verify", h.VerifyAuditChain)
		protected.POST("/audit/repair", h.RepairAuditChain)
		protected.GET("/system/health", h.SystemHealth)
		protected.GET("/alerts", h.ListAlerts)
		protected.GET("/alerts/deliveries", h.ListAlertDeliveries)
		protected.POST("/alerts/:id/deliveries/:channel/retry", h.RetryAlertDelivery)
		protected.POST("/alerts/:id/read", h.MarkAlertRead)
		protected.POST("/alerts/:id/claim", h.ClaimAlert)
		protected.GET("/system/capabilities", h.ListSystemCapabilities)
		protected.POST("/system/capabilities/verify", h.VerifySystemCapabilities)
		protected.GET("/system/config", h.SystemConfigView)
		protected.GET("/system/config/public-key", h.SystemConfigPublicKey)
		protected.POST("/system/config/preflight", h.SystemConfigPreflight)
		protected.POST("/system/config/apply", h.SystemConfigApply)
		protected.GET("/system/ragflow/sync/settings", h.ResourceSyncSettingView)
		protected.PATCH("/system/ragflow/sync/settings", h.ResourceSyncSettingUpdate)
		protected.GET("/system/ragflow/sync/mappings", h.ListResourceSyncTenantMappings)
		protected.POST("/system/ragflow/sync/mappings", h.UpsertResourceSyncTenantMapping)
		protected.DELETE("/system/ragflow/sync/mappings/:externalTenantId", h.DeleteResourceSyncTenantMapping)
		protected.POST("/system/ragflow/sync/scan", h.ScanResourceSync)
		protected.GET("/system/ragflow/sync/runs", h.ListResourceSyncRuns)
		protected.GET("/system/ragflow/sync/runs/:id", h.GetResourceSyncRun)
		protected.GET("/system/ragflow/sync/runs/:id/items", h.ListResourceSyncRunItems)
		protected.POST("/system/ragflow/sync/runs/:id/import", h.ImportResourceSync)
		protected.POST("/system/ragflow/sync/runs/:id/assign", h.AssignResourceSyncItems)
		protected.POST("/system/ragflow/sync/reconcile", h.ReconcileResourceSync)
		protected.GET("/system/ragflow/sync/resources", h.ListResourceSyncResources)
		protected.GET("/system/ragflow/sync/relink/tenant-options", h.ListResourceSyncRelinkTenantOptions)
		protected.GET("/system/ragflow/sync/relink/resource-options", h.ListResourceSyncRelinkResourceOptions)
		protected.GET("/system/ragflow/sync/resources/:type/:externalTenantId/:id/versions", h.ListResourceBindingVersions)
		protected.GET("/system/ragflow/sync/artifacts/:id", h.GetResourceSyncArtifact)
		protected.POST("/system/ragflow/sync/resources/:type/:externalTenantId/:id/relink", h.RelinkResourceSync)
		protected.POST("/system/ragflow/sync/resources/:type/:externalTenantId/:id/conflicts/resolve", h.ResolveResourceSyncConflict)
		protected.GET("/system/settings", h.SystemSettingsView)
		protected.PATCH("/system/settings", h.SystemSettingsUpdate)
		protected.GET("/system/settings/revisions", h.ListSystemSettingRevisions)
		protected.GET("/system/settings/revisions/:id", h.GetSystemSettingRevision)
		protected.POST("/system/settings/revisions/:id/rollback", h.RollbackSystemSettingRevision)
		protected.POST("/system/settings/secrets/:key", h.UpdateSystemSettingSecret)
		protected.GET("/users", h.ListUsers)
		protected.POST("/users", h.CreateUser)
		protected.PUT("/users/:id/status", h.SetUserStatus)
		protected.PUT("/users/:id", h.UpdateUserProfile)
		protected.PUT("/users/:id/role", h.AssignRole)
		protected.DELETE("/users/:id", h.DeleteUser)
		protected.GET("/roles", h.ListRoles)
		protected.GET("/roles/permission-catalog", h.GetPermissionCatalog)
		protected.POST("/roles", h.CreateRole)
		protected.PUT("/roles/:id", h.UpdateRole)
		protected.DELETE("/roles/:id", h.DeleteRole)
		protected.GET("/roles/:id/permissions", h.GetRolePermissions)
		protected.POST("/chat/completions", h.UserChatCompletion)
		protected.POST("/chat/upload", h.UploadChatFile)
		protected.GET("/chat/reference", h.ChatChunk)
		protected.GET("/chat/document/chunks", h.ChatDocChunks)
		protected.GET("/chat/document/preview", h.ChatDocPreview)
		protected.GET("/chat/image", h.ChatImage)
		protected.POST("/chat/feedback", h.ChatFeedback)
		protected.GET("/chats", h.ListChats)
		protected.GET("/chats/model-options", h.GetChatModelOptions)
		protected.POST("/chats/batch-status", h.BatchUpdateChatStatus)
		protected.POST("/chats", h.CreateChat)
		protected.DELETE("/chats", h.BatchDeleteChats)
		protected.GET("/chats/:id", h.GetChat)
		protected.GET("/chats/:id/usage", h.ChatUsage)
		protected.GET("/chats/:id/config", h.GetChatConfig)
		protected.PUT("/chats/:id", h.UpdateChat)
		protected.DELETE("/chats/:id", h.DeleteChat)
		protected.GET("/chats/:id/sessions", h.ListChatSessions)
		protected.POST("/chats/:id/sessions", h.CreateChatSession)
		protected.GET("/chats/:id/sessions/:sessionId", h.GetChatSession)
		protected.GET("/chats/:id/sessions/:sessionId/messages", h.ListChatSessionMessages)
		protected.PATCH("/chats/:id/sessions/:sessionId", h.UpdateChatSession)
		protected.DELETE("/chats/:id/sessions/:sessionId", h.DeleteChatSession)
		protected.DELETE("/chats/:id/sessions", h.DeleteChatSessions)
		protected.GET("/search-apps", h.ListSearchApps)
		protected.POST("/search-apps", h.CreateSearchApp)
		protected.GET("/search-apps/model-options", h.SearchAppModelOptions)
		protected.GET("/search-apps/:id", h.GetSearchApp)
		protected.PUT("/search-apps/:id", h.UpdateSearchApp)
		protected.GET("/search-apps/:id/config", h.GetSearchAppConfig)
		protected.DELETE("/search-apps/:id", h.DeleteSearchApp)
		protected.POST("/search-apps/:id/completion", h.SearchAppCompletion)
		protected.POST("/search-apps/:id/completion/stream", h.StreamSearchAppCompletion)
		protected.GET("/memories", h.ListMemories)
		protected.GET("/memories/model-options", h.MemoryModelOptions)
		protected.POST("/memories", h.CreateMemory)
		protected.GET("/memories/:id", h.GetMemory)
		protected.GET("/memories/:id/config", h.GetMemoryConfig)
		protected.PUT("/memories/:id", h.UpdateMemory)
		protected.DELETE("/memories/:id", h.DeleteMemory)
		protected.GET("/memories/:id/messages", h.ListMemoryMessages)
		protected.POST("/memories/:id/messages", h.AddMemoryMessage)
		protected.GET("/memories/:id/messages/search", h.SearchMemoryMessages)
		protected.GET("/memories/:id/messages/:messageId/content", h.GetMemoryMessageContent)
		protected.PUT("/memories/:id/messages/:messageId", h.UpdateMemoryMessageStatus)
		protected.DELETE("/memories/:id/messages/:messageId", h.DeleteMemoryMessage)
		protected.GET("/agents", h.ListAgents)
		protected.POST("/agents", h.CreateAgent)
		protected.GET("/agents/:id", h.GetAgent)
		protected.GET("/agents/:id/detail", h.GetAgentDetail)
		protected.PUT("/agents/:id", h.UpdateAgent)
		protected.POST("/agents/:id/publish", h.PublishAgent)
		protected.DELETE("/agents/:id", h.DeleteAgent)
		protected.GET("/agents/:id/versions", h.ListAgentVersions)
		protected.GET("/agents/:id/versions/:versionId", h.GetAgentVersion)
		protected.POST("/agents/:id/versions/:versionId/rollback", h.RollbackAgentVersion)
		protected.GET("/agents/:id/sessions", h.ListAgentSessions)
		protected.POST("/agents/:id/sessions", h.CreateAgentSession)
		protected.GET("/agents/:id/sessions/:sessionId", h.GetAgentSession)
		protected.GET("/agents/:id/sessions/:sessionId/messages", h.ListAgentSessionMessages)
		protected.DELETE("/agents/:id/sessions/:sessionId", h.DeleteAgentSession)
		protected.POST("/agents/:id/upload", h.UploadAgentFile)
		protected.POST("/agents/:id/chat/completions", h.AgentChatCompletion)
		protected.POST("/agents/:id/chat/completions/stream", h.StreamAgentChatCompletion)
		protected.PUT("/roles/:id/permissions", h.SetRolePermissions)
		handler.RegisterGovernanceRoutes(protected, h)

		if cfg.Approval.Enabled {
			protected.GET("/approvals", h.ListApprovals)
			protected.POST("/approvals", h.CreateApproval)
			protected.GET("/approvals/export", h.ExportApprovals)
			protected.POST("/approvals/batch-approve", h.BatchApproveApprovals)
			protected.POST("/approvals/batch-reject", h.BatchRejectApprovals)
			protected.GET("/approvals/:id", h.GetApproval)
			protected.POST("/approvals/:id/approve", h.ApproveApproval)
			protected.POST("/approvals/:id/reject", h.RejectApproval)
			protected.POST("/approvals/:id/cancel", h.CancelApproval)
			protected.POST("/approvals/:id/retry", h.RetryApproval)
			protected.GET("/approval-delegations", h.ListApprovalDelegations)
			protected.POST("/approval-delegations", h.CreateApprovalDelegation)
			protected.DELETE("/approval-delegations/:id", h.DeleteApprovalDelegation)
			protected.GET("/approval-policies", h.ListApprovalPolicies)
			protected.POST("/approval-policies", h.SaveApprovalPolicy)
			protected.PUT("/approval-policies/:id", h.SaveApprovalPolicy)
		}
		protected.GET("/model-providers", h.ListModelProviders)
		protected.POST("/model-providers", h.CreateModelProvider)
		protected.DELETE("/model-providers/:id", h.DeleteModelProvider)
		protected.GET("/model-providers/:id", h.GetModelProvider)
		protected.GET("/model-providers/catalog", h.ListAvailableProviders)
		protected.GET("/model-providers/:id/instances", h.ListProviderInstances)
		protected.POST("/model-providers/:id/instances", h.CreateProviderInstance)
		protected.PUT("/model-providers/:id/instances/:instanceId", h.UpdateProviderInstance)
		protected.DELETE("/model-providers/:id/instances", h.DeleteProviderInstances)
		protected.POST("/model-providers/:id/verify", h.VerifyProviderConnection)
		protected.GET("/model-providers/:id/instances/:instanceId/models", h.ListProviderInstanceModels)
		protected.POST("/model-providers/:id/instances/:instanceId/models", h.AddProviderModel)
		protected.PATCH("/model-providers/:id/instances/:instanceId/models/:modelId", h.UpdateProviderModel)
		protected.DELETE("/model-providers/:id/instances/:instanceId/models", h.DeleteProviderModels)
		protected.POST("/model-providers/:id/instances/:instanceId/models/:modelId/test", h.TestProviderModel)
		protected.GET("/enterprise-connections", h.ListEnterpriseConnections)
		protected.POST("/enterprise-connections", h.CreateEnterpriseConnection)
		protected.GET("/enterprise-connections/:id", h.GetEnterpriseConnection)
		protected.PUT("/enterprise-connections/:id", h.UpdateEnterpriseConnection)
		protected.GET("/enterprise-connections/:id/versions", h.ListEnterpriseConnectionVersions)
		protected.POST("/enterprise-connections/:id/rotate-credential", h.RotateEnterpriseConnectionCredential)
		protected.POST("/enterprise-connections/:id/deprecate", h.DeprecateEnterpriseConnection)
		protected.POST("/enterprise-connections/:id/retire", h.RetireEnterpriseConnection)
		protected.POST("/enterprise-connections/:id/test", h.TestEnterpriseConnection)
		protected.GET("/enterprise-connections/:id/health", h.GetEnterpriseConnectionHealth)
		protected.GET("/enterprise-connections/:id/availability", h.GetEnterpriseConnectionAvailability)
		protected.GET("/enterprise-connections/:id/bindings", h.ListEnterpriseBindings)
		protected.GET("/enterprise-connections/:id/bindings/:bindingId", h.GetEnterpriseBinding)
		protected.POST("/enterprise-connections/:id/bindings", h.CreateEnterpriseBinding)
		protected.PUT("/enterprise-connections/:id/bindings/:bindingId", h.UpdateEnterpriseBinding)
		protected.POST("/enterprise-connections/:id/bindings/:bindingId/revoke", h.RevokeEnterpriseBinding)
		protected.GET("/enterprise-connections/:id/bindings/:bindingId/versions", h.ListEnterpriseBindingVersions)
		protected.GET("/model-routes", h.ListModelRoutes)
		protected.POST("/model-routes", h.CreateModelRoute)
		protected.PUT("/model-routes/:id", h.UpdateModelRoute)
		protected.DELETE("/model-routes/:id", h.DeleteModelRoute)
		protected.POST("/model-routes/:id/enterprise-pin", h.PinEnterpriseModelRoute)
		protected.GET("/model-routes/:id/enterprise-pins", h.ListEnterpriseModelRoutePins)
		protected.GET("/keys", h.ListAPIKeys)
		protected.POST("/keys", h.CreateAPIKey)
		protected.POST("/keys/:id/revoke", h.RevokeAPIKey)
	}
	// Rate limit per API key (hashed bearer token), not per IP, so tenants
	// behind a shared egress IP get independent buckets.
	r.POST("/v1/chat/completions",
		middleware.RateLimitStrict(limiter, middleware.BearerKey, int64(cfg.Gateway.RateLimitPerMin), time.Minute),
		h.GatewayChat)
	r.POST("/v1/search-apps/:id/completions",
		middleware.RateLimitStrict(limiter, middleware.BearerKey, int64(cfg.Gateway.RateLimitPerMin), time.Minute),
		h.GatewaySearchApp)
	r.POST("/v1/agents/:id/completions",
		middleware.RateLimitStrict(limiter, middleware.BearerKey, int64(cfg.Gateway.RateLimitPerMin), time.Minute),
		h.GatewayAgent)

	return r
}

func ginMode(mode string) string {
	switch mode {
	case "release", "test":
		return mode
	default:
		return gin.DebugMode
	}
}
